# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
<<<<<<< HEAD
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
=======
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MKEPL Java With Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
>>>>>>> 8137a9ba8a31a28d8fae955ba4b70ca9ad0c1ae8

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
<<<<<<< HEAD
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
=======
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
>>>>>>> 8137a9ba8a31a28d8fae955ba4b70ca9ad0c1ae8
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
